#! /bin/sh

text=$(awk 'NR!=1{print $1}' ../size.txt)
data=$(awk 'NR!=1{print $2}' ../size.txt)
bss=$(awk 'NR!=1{print $3}' ../size.txt)

flash=$(($text+$data))
ram=$(($data+$bss))
flash_total=474096
ram_total=125952
flash_perc=$(($flash * 100 / $flash_total))
ram_perc=$(($ram * 100 / $ram_total))

echo "Flash Usage: $flash / $flash_total ($flash_perc%)"
echo "RAM Usage: $ram / $ram_total ($ram_perc%)"
